- hosts: app
  roles:
    - role: docker
      docker-gpg-url: https://download.docker.com/linux/ubuntu/gpg
    - role: nginx
  become: true
  vars:
    default_container_name: docker
    default_container_image: timurbabs/django
    repo_name: https://github.com/mdn/django-locallibrary-tutorial.git

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - net-tools
          - virtualenv
          - python3-setuptools
          - python3-dev
          - python3-virtualenv
          - python3-pip
          - tcl-dev
          - tk-dev
          - python3-tk
          - git
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull default Docker image
      community.docker.docker_image:
        name: "{{ default_container_image }}"
        source: pull
        
    - name: Clone a github repository
      git:
       repo: "{{ repo_name }}"
       dest: /home/repos
       clone: yes
       update: yes

    - name: Create default containers
      community.docker.docker_container:
        name: "{{ default_container_name }}1"
        image: "{{ default_container_image }}"
        state: present
        
- hosts: web
  roles:
    - role: nginx
  become: true
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
   
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - net-tools
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true  
