# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false
  config.vm.network  "public_network"
  config.vm.provider "vmware_desktop" do |v|
    v.ssh_info_public = true
  end
end
